### ISSUE TITLE
httpie thinks it is redirecting output when run from cron

### ISSUE THREAD

**Issue by JonLundy** [jkbrzt/httpie#402] opened 2015-10-29 14:41 UTC
I have the following script:

```
#!/bin/bash
http -d -o address.txt GET "ipinfo.io"
```

which will run normally from the command line. When it runs from cron, I get the following error: 

```
http: error: Cannot use --output, -o with redirected output.
```

Possibly related to #290

**Comment by jkbrzt** [comment] 2015-10-29 20:29
Thanks for the report, @JonLundy. Yes, it is indeed a duplicate of #290.

**Closed by jkbrzt** 2015-10-29 20:29 UTC
Labels: bug, duplicate
