### ISSUE TITLE
Incorrectly issues a GET request instead of POST when given a valid --session

### ISSUE THREAD

**Issue by raphaelh** [jkbrzt/httpie#364] opened 2015-06-25 19:29 UTC
When the session file exists, httpie issues a GET request even though it was told to issue a POST:
```
$ http --pretty=all --verbose --session="$SESSIONFILE" --follow --form POST "$BASEURL" _token="$TOKEN" _task="login" _action="login" _user="$USER" _pass="$PASS"
GET /roundcube/?_task=mail HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Cookie: roundcube_sessid=hr9nh5kh898l8p96o9l4q2gdq4; roundcube_sessid=o41hfqjhsg1coe84vpnnpn7415; roundcube_sessauth=S45bd81346b5fadf9c8e43669cd32fa957611783f
Host: demo.linuxsolutions.com.br
User-Agent: HTTPie/0.8.0
```

When the session file doesn't exist (notice `xx` at the end of `--session="$SESSIONFILE"`), httpie correctly issues a POST request:
```
$ http --pretty=all --verbose --session="$SESSIONFILE"xx --follow --form POST "$BASEURL" _token="$TOKEN" _task="login" _action="login" _user="$USER" _pass="$PASS"
POST /roundcube/ HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Content-Length: 117
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: demo.linuxsolutions.com.br
User-Agent: HTTPie/0.8.0

_token=f5a7c5fdb3e95d4686606402a1998883&_task=login&_action=login&_user=demo%40linuxsolutions.com.br&_pass=%23demo%24
```

You can find the full script here: https://github.com/raphaelh/roundcube_scripts/blob/master/rc_unread_httpie.sh

**Comment by jakubroztocil** [comment] 2015-06-26 15:16
I'm unable to reproduce this. Could you provide a minimal example? 

```bash
$ http -v --session=issue364 httpbin.org/post foo=bar | grep POST
POST /post HTTP/1.1
$ http -v --session=issue364 httpbin.org/post foo=bar | grep POST
POST /post HTTP/1.1
```

**Comment by raphaelh** [comment] 2015-06-30 21:53
Try this script: https://gist.github.com/raphaelh/3b65bd16fb6e2662e412

Run it several times, it will alternatively issue GET and POST

**Comment by jakubroztocil** [comment] 2015-06-30 23:03
When you remove `--follow` from the command, you get `POST` every time. It's because currently, only the last request/response is output when a redirect is `--follow`ed. A limitation that should be fixed soon.

**Comment by raphaelh** [comment] 2015-07-01 16:53
Thanks for your quick reply. So is there a workaround at the moment?

**Comment by raphaelh** [comment] 2015-07-30 06:55
Any update on this issue?

**Comment by jkbrzt** [comment] 2016-02-29 15:45
@raphaelh the current master has a new `--show-redirects` option

**Closed by jkbrzt** 2016-02-29 15:45 UTC
Labels: bug, needs input
