### ISSUE TITLE
JSON from stdin with --json is posted as "string"

### ISSUE THREAD

**Issue by alex88** [jkbrzt/httpie#379] opened 2015-09-09 09:26 UTC
I'm trying to POST and empty JSON `{}` I've tried to use

```
echo -n '{}' | http -j -v POST someurl
```

however, the json is sent as string enclosed in quotes:

```
POST /xxx HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 4
Content-Type: application/json
User-Agent: HTTPie/0.9.2

"{}"
```

how can I POST that empty json without quotes?

**Comment by jkbrzt** [comment] 2015-09-09 09:30
I'm unable to reproduce this:

```bash
$ echo -n '{}' | http -jv httpbin.org/post
```

```http
POST /post HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 4
Content-Type: application/json
Host: httpbin.org
User-Agent: HTTPie/0.9.2
```

What version of httpie are you using?

```bash
$ http --version
0.9.2
```

**Comment by jkbrzt** [comment] 2015-09-09 09:34
Thanks for the report. The `-j, --json` option doesn't seem to work well with JSON data passing in via `STDIN` in general — this should fixed.

For now, you set the correct Content-Type yourself:

```sh
$ echo -n '{}' | http -v httpbin.org/post Content-Type:application/json
```

**Comment by alex88** [comment] 2015-09-09 09:35
Oh right that works, thanks for the temp workaround!

**Comment by csuttles** [comment] 2015-10-07 15:27
I notice Alex88 is using 0.9.2; Perhaps this is already fixed in the latest version? I took a look at this and I was unable to duplicate the issue on the current dev release (1.0.0). The perl at the end is just masking my ip address (nothing to see here, move along).

Anyway, HTH, and thanks for the handy tool. The dump of the source and remote headers with color/highlighting is super nice.

Cheers.

```
✘-2 ~/src/httpie [cjs_httpie_issue_379|…1]
08:17 $ echo -n $JSON | http  -j -v POST http://httpbin.org/post | perl -p -e 's/(\d+\.){3}\d+/0.0.0.0/'
POST /post HTTP/1.1
Content-Length: 25
Accept-Encoding: gzip, deflate
Host: httpbin.org
Accept: application/json
User-Agent: HTTPie/1.0.0-dev
Connection: keep-alive
Content-Type: application/json

{ "cannot": "duplicate" }

HTTP/1.1 200 OK
Server: nginx
Date: Wed, 07 Oct 2015 15:17:23 GMT
Content-Type: application/json
Content-Length: 435
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
  "args": {},
  "data": "{ \"cannot\": \"duplicate\" }",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "application/json",
    "Accept-Encoding": "gzip, deflate",
    "Content-Length": "25",
    "Content-Type": "application/json",
    "Host": "httpbin.org",
    "User-Agent": "HTTPie/1.0.0-dev"
  },
  "json": {
    "cannot": "duplicate"
  },
  "origin": "0.0.0.0",
  "url": "http://httpbin.org/post"
}
✔ ~/src/httpie [cjs_httpie_issue_379|…1]
08:17 $ echo -n $JSON | http -v httpbin.org/post Content-Type:application/json | perl -p -e 's/(\d+\.){3}\d+/0.0.0.0/'
POST /post HTTP/1.1
Content-Length: 25
Accept-Encoding: gzip, deflate
Host: httpbin.org
Accept: application/json
User-Agent: HTTPie/1.0.0-dev
Connection: keep-alive
Content-Type: application/json

{ "cannot": "duplicate" }

HTTP/1.1 200 OK
Server: nginx
Date: Wed, 07 Oct 2015 15:18:07 GMT
Content-Type: application/json
Content-Length: 435
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
  "args": {},
  "data": "{ \"cannot\": \"duplicate\" }",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "application/json",
    "Accept-Encoding": "gzip, deflate",
    "Content-Length": "25",
    "Content-Type": "application/json",
    "Host": "httpbin.org",
    "User-Agent": "HTTPie/1.0.0-dev"
  },
  "json": {
    "cannot": "duplicate"
  },
  "origin": "0.0.0.0",
  "url": "http://httpbin.org/post"
}

...

✘-1 ~/src/httpie [cjs_httpie_issue_379|…1]
08:18 $ echo $JSON
{ "cannot": "duplicate" }
```

```
✔ ~/src/httpie [cjs_httpie_issue_379|…1]
08:18 $ export JSON='{}'

✔ ~/src/httpie [cjs_httpie_issue_379|…1]
08:18 $ echo -n $JSON | http  -j -v POST http://httpbin.org/post | perl -p -e 's/(\d+\.){3}\d+/0.0.0.0/'
POST /post HTTP/1.1
Content-Length: 2
Accept-Encoding: gzip, deflate
Host: httpbin.org
Accept: application/json
User-Agent: HTTPie/1.0.0-dev
Connection: keep-alive
Content-Type: application/json

{}

HTTP/1.1 200 OK
Server: nginx
Date: Wed, 07 Oct 2015 15:18:33 GMT
Content-Type: application/json
Content-Length: 378
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
  "args": {},
  "data": "{}",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "application/json",
    "Accept-Encoding": "gzip, deflate",
    "Content-Length": "2",
    "Content-Type": "application/json",
    "Host": "httpbin.org",
    "User-Agent": "HTTPie/1.0.0-dev"
  },
  "json": {},
  "origin": "0.0.0.0",
  "url": "http://httpbin.org/post"
}
✔ ~/src/httpie [cjs_httpie_issue_379|…1]
08:18 $ echo -n $JSON | http -v httpbin.org/post Content-Type:application/json | perl -p -e 's/(\d+\.){3}\d+/0.0.0.0/'
POST /post HTTP/1.1
Content-Length: 2
Accept-Encoding: gzip, deflate
Host: httpbin.org
Accept: application/json
User-Agent: HTTPie/1.0.0-dev
Connection: keep-alive
Content-Type: application/json

{}

HTTP/1.1 200 OK
Server: nginx
Date: Wed, 07 Oct 2015 15:18:39 GMT
Content-Type: application/json
Content-Length: 378
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
  "args": {},
  "data": "{}",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "application/json",
    "Accept-Encoding": "gzip, deflate",
    "Content-Length": "2",
    "Content-Type": "application/json",
    "Host": "httpbin.org",
    "User-Agent": "HTTPie/1.0.0-dev"
  },
  "json": {},
  "origin": "0.0.0.0",
  "url": "http://httpbin.org/post"
}
```

**Comment by Altreus** [comment] 2015-11-20 17:04
Hiya

I just came across this bug because I was on 0.8.0 and someone else was on 0.9.0 and we spent ages trying to figure it out!

I can confirm that 0.8.0 was fine; 0.9.0 is broken all the way up to 0.9.2; and it works again in 1.0.0-dev

**Comment by mkjsix** [comment] 2015-12-26 17:11
Hi all,
Same problem verified here. It works with 0.8.0 but it's broken with 0.9.2, unless we remove the `--json` parameter.

With 0.8.0 and `--json`
```
$ (master) echo '{"name": "John"}' | http -v --json PATCH 127.0.0.1:8080/person/1 X-API-Token:123
PATCH /person/1 HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Content-Length: 17
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:8080
User-Agent: HTTPie/0.8.0
X-API-Token: 123

{
   "name": "John"
}
...
```

With 0.9.2 and `--json`
```
echo '{"name": "John"}' | http -v --json PATCH 127.0.0.1:8080/person/1 X-API-Token:123
PATCH /person/1 HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 24
Content-Type: application/json
Host: 127.0.0.1:8080
User-Agent: HTTPie/0.9.2
X-API-Token: 123

"{\"name\": \"John\"}\n"
...
```

With 0.9.2 without `--json`:
```
echo '{"name": "John"}' | http -v PATCH 127.0.0.1:8080/person/1 X-API-Token:123
PATCH /person/1 HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 17
Content-Type: application/json
Host: 127.0.0.1:8080
User-Agent: HTTPie/0.9.2
X-API-Token: 123

{
   "name": "John"
}
...
```

**Comment by jkbrzt** [comment] 2016-02-28 09:08
I'm unable to reproduce this neither in HTTPie v 0.9.3 nor in dev. If you're still having the issue, would you please post the output of `http --debug` here?

**Comment by jkbrzt** [comment] 2016-02-29 15:20
Closing for now. Feel free to reopen if you're still having this issue.

**Closed by jkbrzt** 2016-02-29 15:20 UTC
Labels: bug
