### ISSUE TITLE
Multiple the same headers in request

### ISSUE THREAD

**Issue by SshPwd** [jkbrzt/httpie#525] opened 2016-10-07 20:38 UTC
From http RFC:

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded.

`http -v GET localhost:12345 X-Your-Some-Header:"yo yo" X-Your-Some-Header:"bar"`

```
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:12345
User-Agent: HTTPie/0.9.4
X-Your-Some-Header: bar
localhost: 12345
```

**Comment by jkbrzt** [comment] 2016-10-12 15:09
Duplicate of: #130

As a work-around you can do the concatenation yourself:

```
http -v GET localhost:12345 X-Your-Some-Header:"yo yo, bar"`
```

**Closed by jkbrzt** 2016-10-12 15:09 UTC
